- name: Install unattended-upgrades-pinfiles
  template:
    src: unattended-upgrades-pinfiles.j2
    dest: /usr/local/bin/unattended-upgrades-pinfiles
    mode: 0700

- name: Create /etc/systemd/system/apt-daily-upgrade.service.d directory
  file:
    path: /etc/systemd/system/apt-daily-upgrade.service.d
    state: directory

- name: Install ExecPre
  copy:
    dest: /etc/systemd/system/apt-daily-upgrade.service.d/unattended-upgrades-minor-only.conf
    content: |
      [Service]
      ExecStartPre=/usr/local/bin/unattended-upgrades-pinfiles install
      ExecStartPost=/usr/local/bin/unattended-upgrades-pinfiles remove
  register: __unattended_upgrades_minor_only

- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: yes
  when: __unattended_upgrades_minor_only is changed


